import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";
import WalletUIStyles from "./wallet-ui-styles";
import { ReactQueryProvider } from "../lib/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Netuno App",
  description: "Generated by SMKRSSN",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <body className={geistSans.className}>
        <ReactQueryProvider>
          <Providers>
            <WalletUIStyles />
            {children}
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
